//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Cajeros.Repositorio
{
    
    
    public class ComportamientoMetaData
    {
    	[Key]
        [Required]
        public virtual int IdComportamiento
        {
            get;
            set;
        }
        public virtual Nullable<int> Cant50
        {
            get;
            set;
        }
        public virtual Nullable<int> Cant20
        {
            get;
            set;
        }
        public virtual Nullable<int> Cant10
        {
            get;
            set;
        }
        public virtual Nullable<int> Pago50
        {
            get;
            set;
        }
        public virtual Nullable<int> Pago20
        {
            get;
            set;
        }
        public virtual Nullable<int> Pago10
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> Fecha
        {
            get;
            set;
        }
        public virtual Nullable<int> IdCajero
        {
            get;
            set;
    
        }
    }
}
