//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cajeros.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(ComportamientoMetaData))]
    public partial class Comportamiento
    {
        public int IdComportamiento { get; set; }
        public Nullable<int> Cant50 { get; set; }
        public Nullable<int> Cant20 { get; set; }
        public Nullable<int> Cant10 { get; set; }
        public Nullable<int> Pago50 { get; set; }
        public Nullable<int> Pago20 { get; set; }
        public Nullable<int> Pago10 { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdCajero { get; set; }
    
        public virtual Cajero Cajero { get; set; }
    }
}
