//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cajeros.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(RutaMetaData))]
    public partial class Ruta
    {
        public int IdRuta { get; set; }
        public int IdCajero { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Cumplido { get; set; }
    
        public virtual Cajero Cajero { get; set; }
    }
}
