//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Cajeros.Repositorio
{
    
    
    public class RutaMetaData
    {
    	[Key]
        [Required]
        public virtual int IdRuta
        {
            get;
            set;
        }
        [Required]
        public virtual int IdCajero
        {
            get;
            set;
    
        }
        [Required]
        public virtual System.DateTime Fecha
        {
            get;
            set;
        }
        [Required]
        public virtual bool Cumplido
        {
            get;
            set;
        }
    }
}
